version: '3.7'

services:
  redis:
    image: "redis:4.0"
    volumes:
       - "redis:/data"
  db:
    image: mysql:5.7.24
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
    env_file: .env
    environment:
      RAILS_ENV: development
    stdin_open: true
    tty: true
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - db
      - redis
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
    stdin_open: true
    tty: true
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh
  proxy:
    image: nginx
    volumes: # mount custom config at runtime
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app:app # "app" is the hostname used in proxy_pass directive
    ports:
      - 80:80
volumes:
  db-data:
  redis:
